version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: mkdir -p /tmp/artifacts
      - run: make
      - run: ./hello
      - run: cp hello /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
