version: 2
jobs:
  build_x86:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: mkdir -p /tmp/artifacts
      - run: make
      - run: ./hello
      - run: cp hello /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
  build_arm:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: mkdir -p /tmp/artifacts
      - run: sudo apt install g++-arm-linux-gnueabihf
      - run: arm-linux-gnueabihf-gcc -o hello_arm hello.c
      - run: cp hello_arm /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_x86
      - build_arm
