version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: make
      - run: ./hello
      - run: cp -p hello $CIRCLE_ARTIFACTS

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
