version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: make
      - run: ./hello
      - store_artifacts:
        path: ~/hello
        destination: hello

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
